alias up='apt update; apt upgrade -y'
alias py='python'
alias gtc='git clone'
alias cds='cd /sdcard'
alias scb='source .bashrc'
alias cla='clang -o main main.c'
alias g23='gcc -std=c23 -g -o main main.c'
alias g17='gcc -std=c17 -g -o main main.c'
alias iall='apt install dex2jar aapt aapt2 apksigner radare2 gdb ltrace binutils apksigner strace d8 hexedit nmap valgrind ninja neovim tmux fish man clang python2 python nodejs ruby php nginx apache2 gnupg busybox openssh openssl clamav fastfetch yara wget bore -y' 
alias sqli='sqlmap -u'
alias x='ls -all'
alias xx='echo *'
alias c='cat'
alias apa='whatis'
alias neo='fastfetch -c hardware -l slackware'
alias t3rm='chsh -s fish'
alias xt3rm='chsh -s bash'
alias 0x='nvim'
PS1='✓\[\e[1;32m\]player@\[\e[1;34m\]ctf\[\e[0m\] >> '
alias serveo='ssh -R 80:localhost:8989 serveo.net'
alias web='busybox httpd -p 8989'
alias ncl='nc -l 9090'
alias i='whoami'
alias clr='history -c'
alias Zcr4ck='https://github.com/ariadesupriyatna/Zcr4ck'
alias Gpeda='git clone https://github.com/longld/peda.git ~/peda && echo "source ~/peda/peda.py" >> ~/.gdbinit && echo "DONE! debug your program with gdb and enjoy"'
alias LCT='npm install -g localtunnel && lt --port 8000'
alias str='strace -f ./binary'
